#
# File:- Makefile for ManiX OS
# written by Manish Regmi (manish_regmi@hotmail.com)
#
# Makefile for easy compilation.:-)
# file= /arch/


all:
	make -C i386
	
clear:

	make -C i386 clear
	


