/*
 * BUS manager for ManRiX OS
 * Copyright (C) 2004, 2005	Manish Regmi (regmi dot manish at gmail dot com)
 *				            Rajesh R.C (rajee5283 at hotmail dot com)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
/*
 * File: pcidevs2c.c
 * 		A small utility to convert Craig Hart's pcidevs.txt to a c file.
 */

/*
 * TODO: Write it on Sorted order and use good searching algorithm to retrieve the names.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static FILE *in, *out;

static inline int readline(unsigned short *id, char *str)
{
	char etype, ch;
	char eid[5];
	int index, ret = 0, len;
	do{
		etype = fgetc(in);
		if(etype == ';')
			fgets(str, 80, in);//while(fgetc(in) != '\n');

		if((etype == 'V') || (etype == 'D'))
		{
			fgetc(in);
			for(index = 0; index < 4; index++)
			{
				eid[index] = fgetc(in);
			}
			eid[4] = '\0';

			*id = (unsigned short)strtol(eid, (char **)NULL, 16);
			fgetc(in);
			//ptr = fgets(str, 80, in); dont use this?
			for(index = 0; index < 80; index++)
			{
				ch = fgetc(in);
				if(ch == '\n')
					break;

				if((ch == '"')||(ch == '?'))
				{
					str[index++] = '\\';
				}

				str[index] = ch;

			}
			str[index] = '\0';


			ret = (int)etype;
			break;
		}
		else
		{
			fgets(str, 80, in);
		}
	}while(etype != EOF);

	return ret;
}

int main()
{

	int length, type;
	unsigned short id;
	char str[80], entry[80];
	char *vendors = {
"/* \n"
" * BUS manager for ManRiX OS\n"
" * Copyright (C) 2004, 2005	Manish Regmi (regmi dot manish at gmail dot com)\n"
" *				Rajesh R.C (rajee5283 at hotmail dot com)\n"
" *\n"
" * This program is free software; you can redistribute it and/or modify\n"
" * it under the terms of the GNU General Public License as published by\n"
" * the Free Software Foundation; either version 2 of the License, or\n"
" * (at your option) any later version.\n"
" *\n"
" * This program is distributed in the hope that it will be useful,\n"
" * but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
" * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
" * GNU General Public License for more details.\n"
" *\n"
" * You should have received a copy of the GNU General Public License\n"
" * along with this program; if not, write to the Free Software\n"
" * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA\n"
" */\n"
"/*\n"
" * File: pciid.c\n"
" * 		PCI Device and Vendor's Id list based on Craig Hart's pcidevs.txt.\n"
" * 	Automatically Generated By pciscan (pcidevs2c.c)\n"
" */\n"
"\n"
"#include \"pci.h\"\n\n"

"struct pciid vendors[] = {\n"};

	in = fopen("pcidevs.txt", "r");
	if(!in)
	{
		perror("Error opening pcidevs.txt: ");
		exit(1);
	}
	out = fopen("pciid.c","w");
	if(!out)
	{
		perror("Error opening/creating pciid.c: ");
		exit(1);
	}


	length = strlen(vendors);
	fwrite(vendors, 1, length, out);

	while((type = readline(&id, str)) != 0)
		fprintf(out, "\t{ '%c', 0x%X, \"%s\" },\n", (char)type, id, str);

	fprintf(out, "\t{ 'N', 0x0, NULL }\n};\n");

/*	fseek(in, 0, SEEK_SET);
	fprintf(out, "struct pciid devices[] = {\n");
	while(readline('D', &id, str) == 0)
		fprintf(out, "\t{ 0x%X, \"%s\" },\n", id, str);

	fprintf(out, " { 0x0, NULL }\n};\n\t");
*/
	fclose(in);
	fclose(out);
	return 0;
}
